### ISSUE TITLE
TypeError: Cannot read property 'utils' of undefined

### ISSUE THREAD

**Issue by gcobr** [SAPessi/serverless-sam#40]
Having the following error with:
- Serverless 1.77.0
- Serverless SAM Plugin 0.2.0

~~~bash
# sls sam export --env local --output ./file.yml
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command sam
Serverless: Load command sam:export
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke sam:export
Serverless: Working folder: /src/node_modules/serverless-sam
Serverless: Validate
Serverless: Preparing original CloudFormation template
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'utils' of undefined
      at Service.loadServiceFileParam (/usr/lib/node_modules/serverless/lib/classes/Service.js:63:37)
      at /usr/lib/node_modules/serverless/lib/classes/Service.js:53:26
  From previous event:
      at Service.load (/usr/lib/node_modules/serverless/lib/classes/Service.js:53:8)
      at /src/node_modules/serverless-sam/index.js:113:33
      at SamPlugin.validateDefinition (/src/node_modules/serverless-sam/index.js:110:12)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.17.0
     Framework Version:         1.72.0
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.14
~~~

**Comment by markabdallah** [comment]
I'm facing the same issue
